### ISSUE TITLE
建议PopupWindow部分修改一下

### ISSUE THREAD

**Issue by kymjs** [yinchuandong/SelectableTextView#1]
弹出的 Menu，你使用的是 View，在 View 的里面又包含了一个 PopupWindow，而 PopupWindow 本身内部就包含了一个 View，这种做法不仅消耗内存，而且等同于放弃了 PopupWindow 的优势(界面的dismiss交给系统自动处理)。  
在这一块可以修改一下。

----个人的建议。

**Comment by yinchuandong** [comment]
我好像不是这样的，弹出的菜单是一个popupwindow, 每一个cursor是一个popupwindow，popupwindow里面装的是view. 太久之前写的，忘记了细节，sorry啦。如果你有兴趣，可以改一下，发一个Pull request吧
